services:
  db:
    image: postgres:16-alpine
    container_name: cloud-cicd-postgres
    environment:
      POSTGRES_DB: cloudcicd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cloudcicd"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: cloud-cicd-flask
    environment:
      DB_HOST: db
      DB_NAME: cloudcicd
      DB_USER: postgres
      DB_PASS: postgres
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
